// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPVEdtCfsMt1Ot0IiFqon28S9aYwKrGA',
    appId: '1:363959673263:web:567d45bfe51a75b3cd4f5a',
    messagingSenderId: '363959673263',
    projectId: 'train1-4c51d',
    authDomain: 'train1-4c51d.firebaseapp.com',
    storageBucket: 'train1-4c51d.firebasestorage.app',
    measurementId: 'G-RTV8G90SF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVznRrwKRt_9FTdfS-Vumh7drqinxnVQ',
    appId: '1:363959673263:android:860328953ce80418cd4f5a',
    messagingSenderId: '363959673263',
    projectId: 'train1-4c51d',
    storageBucket: 'train1-4c51d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD27lN9GfBrrdlm-_gaeszZzis_3ny73EM',
    appId: '1:363959673263:ios:ad105188e44ed865cd4f5a',
    messagingSenderId: '363959673263',
    projectId: 'train1-4c51d',
    storageBucket: 'train1-4c51d.firebasestorage.app',
    iosClientId: '363959673263-vq9seqfh4rm6lg0s0r9gc6m3i4q7m9mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventMngSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD27lN9GfBrrdlm-_gaeszZzis_3ny73EM',
    appId: '1:363959673263:ios:ad105188e44ed865cd4f5a',
    messagingSenderId: '363959673263',
    projectId: 'train1-4c51d',
    storageBucket: 'train1-4c51d.firebasestorage.app',
    iosClientId: '363959673263-vq9seqfh4rm6lg0s0r9gc6m3i4q7m9mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventMngSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCPVEdtCfsMt1Ot0IiFqon28S9aYwKrGA',
    appId: '1:363959673263:web:e823169cae28217dcd4f5a',
    messagingSenderId: '363959673263',
    projectId: 'train1-4c51d',
    authDomain: 'train1-4c51d.firebaseapp.com',
    storageBucket: 'train1-4c51d.firebasestorage.app',
    measurementId: 'G-NSGRKWF4F0',
  );

}